### ISSUE TITLE
glimmer_dsl_with_active_record sample repo

### ISSUE THREAD

**Issue by chip** [AndyObtiva/glimmer#46]
Hi, I'm really enjoying working with Glimmer and have a small app that I'd like to convert to ActiveRecord (using sqlite3), so I created a bare minimum scaffolded repo as an example: https://github.com/chip/glimmer_dsl_with_active_record.

**Desktop**

- OS [Apple M2 Pro, macOS 13.4 Ventura]
- Java [N/A]
- Ruby version [ruby-3.2.2, chruby 0.3.9]
- Glimmer [glimmer-dsl-libui 0.11.8]

**Issue**

When I execute `glimmer run`, it returns `superclass mismatch for class Hash` as error (see backtrace below for details). I was able to "fix" this by commenting out lines #49-50 on my system in ~/.gem/ruby/3.2.2/gems/concurrent-ruby-1.3.3/lib/concurrent-ruby/concurrent/hash.rb (also had to do the same for array.rb and set.rb):

```
  class Hash < HashImplementation
  end
```

I realize this is not a bug in Glimmer per-se, but saw in `lib/glimmer/shim/concurrent.rb` that you had reopened the `Concurrent` module to redefine `Hash`, `Array`, and `Set` and thought you might at least have a suggestion as to a path forward for a bonafide fix.

I'll be happy to close if this is unnecessary noise.

At any rate, Thanks again for this great DSL!
chip

**Backtrace**

λ glimmer run                                           
Launching Glimmer Application: ./bin/glimmer_dsl_with_active_record
Launching Glimmer Application: /Users/chip/code/ruby/glimmer_dsl_with_active_record/app/glimmer_dsl_with_active_record/launch.rb
/Users/chip/.gem/ruby/3.2.2/gems/concurrent-ruby-1.3.3/lib/concurrent-ruby/concurrent/hash.rb:62:in `<module:Concurrent>': superclass mismatch for class Hash (TypeError)
	from /Users/chip/.gem/ruby/3.2.2/gems/concurrent-ruby-1.3.3/lib/concurrent-ruby/concurrent/hash.rb:5:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/.gem/ruby/3.2.2/gems/i18n-1.14.5/lib/i18n.rb:4:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/.gem/ruby/3.2.2/gems/activesupport-7.1.3.4/lib/active_support/i18n.rb:7:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/.gem/ruby/3.2.2/gems/activesupport-7.1.3.4/lib/active_support/inflector/inflections.rb:4:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/.gem/ruby/3.2.2/gems/activesupport-7.1.3.4/lib/active_support/inflections.rb:3:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/.gem/ruby/3.2.2/gems/activesupport-7.1.3.4/lib/active_support/inflector/methods.rb:3:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/.gem/ruby/3.2.2/gems/activesupport-7.1.3.4/lib/active_support/dependencies/autoload.rb:3:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/.gem/ruby/3.2.2/gems/activesupport-7.1.3.4/lib/active_support.rb:27:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/.gem/ruby/3.2.2/gems/activerecord-7.1.3.4/lib/active_record.rb:26:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/code/ruby/glimmer_dsl_with_active_record/app/lib/database.rb:1:in `<top (required)>'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/chip/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/chip/code/ruby/glimmer_dsl_with_active_record/app/glimmer_dsl_with_active_record.rb:18:in `<top (required)>'
	from /Users/chip/code/ruby/glimmer_dsl_with_active_record/app/glimmer_dsl_with_active_record/launch.rb:1:in `require_relative'
	from /Users/chip/code/ruby/glimmer_dsl_with_active_record/app/glimmer_dsl_with_active_record/launch.rb:1:in `<top (required)>'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:124:in `load'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:124:in `launch'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:154:in `launch_application'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:147:in `launch'
	from /Users/chip/code/ruby/glimmer_dsl_with_active_record/bin/glimmer_dsl_with_active_record:8:in `<top (required)>'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:124:in `load'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:124:in `launch'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:154:in `launch_application'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:147:in `launch'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/rake_task.rb:55:in `block (2 levels) in <top (required)>'
	from /Users/chip/.gem/ruby/3.2.2/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
	from /Users/chip/.gem/ruby/3.2.2/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
	from /Users/chip/.gem/ruby/3.2.2/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
	from /Users/chip/.gem/ruby/3.2.2/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
	from /Users/chip/.gem/ruby/3.2.2/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
	from /Users/chip/.gem/ruby/3.2.2/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
	from /Users/chip/.gem/ruby/3.2.2/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:120:in `launch'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:154:in `launch_application'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/lib/glimmer/launcher.rb:147:in `launch'
	from /Users/chip/.gem/ruby/3.2.2/gems/glimmer-dsl-libui-0.11.8/bin/glimmer:30:in `<top (required)>'
	from /Users/chip/.gem/ruby/3.2.2/bin/glimmer:25:in `load'
	from /Users/chip/.gem/ruby/3.2.2/bin/glimmer:25:in `<main>'

**Comment by chip** [comment]
I'm not sure if this is a poor hack, but it fixes my issue.

From *bin/glimmer_dsl_with_active_record*, after shebang line `#!/usr/bin/env ruby`, add the following code:
```ruby

begin
  if Object.constants.include?(:Concurrent)
    Object.send(:remove_const, :Concurrent)
  end
  require 'concurrent'
rescue StandardError => e
  puts "Oops from #{bin/glimmer_dsl_with_active_record}"
  puts e.message
  puts e.backtrace
end
```

I'm happy to have input from anyone who thinks there's a better way, but wanted to add this here in case it helps someone avoid my pain. HTH 😄

**Comment by AndyObtiva** [comment]
Hi, thanks for the kind words.

I didn't get a chance to read your message till now. It is a busy week for me as I am traveling. 

Thank you for sharing the ActiveRecord prototype repo. I will take a look at it.

That error you mentioned would happen if `Hash` is getting defined/redefined as a class in multiple libraries with different superclasses. The shim you mentioned was mainly added so that libraries that need to load Glimmer without concurrent-ruby would function normally (as mentioned in the code, Opal Ruby needed this). But, it should have not caused that error because it does not (re)define Hash as a class, yet it assigns it as a constant. I wonder if a newer version of Ruby became stricter with regard to accepting that. You are using Ruby 3.2.2. I have not tested that functionality with it thoroughly, so it may as well be the culprit. That means, I need to add more logic in the shim file to ensure not loading it if concurrent-ruby is already loaded (so it would load in Opal Ruby, but not standard Ruby where concurrent-ruby is available), or some similar solution. 

I will look into fixing this so that you would not need to add your own workaround quickfix anymore. So, I am reopening the issue and will keep it open until resolved.

I am glad you are not blocked in the meantime.

Cheers,

P.S. You might not need this anymore, but I just wanted to note that I blogged about how to use ActiveRecord/SQLite with Glimmer (Glimmer DSL for SWT specifically) in the past:
https://andymaleh.blogspot.com/2022/06/using-activerecord-with-sqlite-db-in.html

**Comment by chip** [comment]
Hi @AndyObtiva - Thanks for the blog post. It will definitely help me when I add migrations to my app. 😄 

Trying to narrow it down, here's what `ruby-2.7.7`, `ruby-3.0.7`, and `ruby-3.1.2` report:
```
λ chruby ruby-2.7.7

~/code/ruby/glimmer_dsl_with_active_record superclass-mismatch*
λ bundle
Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.5.10). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.5.10`.
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby

    juwelier (= 2.4.9) was resolved to 2.4.9, which depends on
      nokogiri was resolved to 1.16.6, which depends on
        Ruby (>= 3.0.0)

    sqlite3 (~> 1.3) was resolved to 1.7.3, which depends on
      Ruby (>= 2.7)

Ruby (>= 3.0.0), which is required by gem 'sqlite3 (~> 1.3)', is not available in the local ruby installation

λ chruby 
   ruby-2.7.7
 * ruby-3.0.7
   ruby-3.1.2
   ruby-3.1.4
   ruby-3.2.2
   ruby-3.2.4
   ruby-3.3.0
   ruby-3.3.1
   ruby-3.3.3

~/code/ruby/glimmer_dsl_with_active_record superclass-mismatch*
λ bundle 
Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.5.10). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.5.10`.
Fetching gem metadata from https://rubygems.org/......
multi_xml-0.7.1 requires ruby version >= 3.1.2, which is incompatible with the current version, ruby 3.0.7p220

λ chruby      
   ruby-2.7.7
   ruby-3.0.7
 * ruby-3.1.2
   ruby-3.1.4
   ruby-3.2.2
   ruby-3.2.4
   ruby-3.3.0
   ruby-3.3.1
   ruby-3.3.3

~/code/ruby/glimmer_dsl_with_active_record superclass-mismatch*
λ bundle      
Bundle complete! 6 Gemfile dependencies, 88 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

~/code/ruby/glimmer_dsl_with_active_record superclass-mismatch*
λ glimmer run
Launching Glimmer Application: ./bin/glimmer_dsl_with_active_record
Launching Glimmer Application: /Users/chip/code/ruby/glimmer_dsl_with_active_record/app/glimmer_dsl_with_active_record/launch.rb
/Users/chip/.gem/ruby/3.1.2/gems/concurrent-ruby-1.3.3/lib/concurrent-ruby/concurrent/hash.rb:49:in `<module:Concurrent>': superclass mismatch for class Hash (TypeError)
```

I truncated the rest of the log for brevity. I'm kinda stuck here, but will let you know if I discover more clues. Thanks again!

**Comment by AndyObtiva** [comment]
OK, I cracked the cause of this issue! (it is indeed not related to the Ruby version being used)

Glimmer DSL for LibUI does NOT load concurrent-ruby by default, unlike Glimmer DSL for SWT, which does as it needs it for safety of running apps with JRuby's parallel threads. That is why, when I used SQLite/ActiveRecord with Glimmer DSL for SWT, I didn't run into any issues.

I checked an app scaffolded by Glimmer DSL for LibUI WITHOUT a database called Glimmer Snake, and it does not suffer from this issue:
https://github.com/AndyObtiva/glimmer_snake

The reason is because it does NOT load concurrent-ruby

I cloned your app locally and tried it. It turns out, ActiveSupport pulls concurrent-ruby and loads it automatically upon loading bundler, and given that Glimmer DSL for LibUI was not prepared to use concurrent-ruby as it needs to load it BEFORE glimmer (just like Glimmer DSL for SWT does), the order of loading things caused the issue.

If I replace all the code you added with just `require 'concurrent'`, that fixes the issue, but ONLY if I run `bin/glimmer_dsl_with_active_record` directly without using `glimmer run`. 

If i go to `glimmer-dsl-libui` and load `concurrent` inside it before `glimmer` just like I do in `glimmier-dsl-swt`, the issue goes away.

To prevent this issue going forward, I think I am going to have `glimmer-dsl-libui` attempt to load `concurrent` ONLY IF INSTALLED, and otherwise, it would just default to the shim.

I will let you know once I made a release with this fix.

**Comment by chip** [comment]
Nice catch! That's excellent news. 👍🏻
